# https://hub.docker.com/r/pytorch/pytorch/tags
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
ENV MODEL="dinov2-small"
ENV BATCH_SIZE=64
ENV IMAGE_DIR="sdxl_imagenet_8"
RUN pip install --upgrade pip
RUN pip install \
    transformers==4.39.2 \
    pillow \
    pandas \
    datasets
RUN mkdir /data
RUN mkdir /src
WORKDIR /src
COPY embed.dinov2.py /src/embed.dinov2.py
CMD python embed.dinov2.py --model=$MODEL --batch_size=$BATCH_SIZE --image_dir=$IMAGE_DIR