# https://hub.docker.com/r/pytorch/pytorch/tags
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
RUN pip install --upgrade pip
RUN pip install \
    torchbench \
    torchvision \
    timm \
    Pillow \
    matplotlib \
    pandas \
    numpy \
    tensorflow \
    torch \
    pyyaml \
    tensorboardX \
    einops \
    tqdm
RUN mkdir /data
RUN mkdir /ckpt
RUN mkdir /logs
RUN mkdir /src
WORKDIR /src
COPY traineval.pytorch.py /src/traineval.pytorch.py